[general]
temp-day=6500
temp-night=3500
fade=1
; Указываем использовать ручные координаты вместо GeoClue
location-provider=manual

; Москва
; [manual]
; lat=55.75
; lon=37.62

; Санкт-Петербург
[manual]
lat=59.93
lon=30.33