waybar_palette=mono-ash
waybar_base='../../style/style-b&w'
waybar_shape=noop
waybar_accent=noop
gtk_theme=adw-gtk3-dark
bg=#282828
fg=#d8d8d8
muted=#666666
accent=#bfbfbf
accent_alt=#cba6f7
warm=#bfbfbf
ok=#a3be8c
critical=#cc3436
