waybar_palette=nord-night
waybar_base=../../style/style-cachy
waybar_shape=noop
waybar_accent=noop
gtk_theme=adw-gtk3-dark
bg=#111827
fg=#cdd6f4
muted=#707d9d
accent=#7d9bba
accent_alt=#0ac681
warm=#f0932b
ok=#26a65b
critical=#f53c3c
