waybar_palette=omarchy-tokyo-night
waybar_base=../../style/style-default_alter
waybar_shape=noop
waybar_accent=noop
gtk_theme=adw-gtk3-dark
bg=#222436
fg=#ffffff
muted=#7984a4
accent=#7da6ff
accent_alt=#bb9af7
warm=#ff9e64
ok=#b9f27c
critical=#ff0000
