waybar_palette=graphite-violet
waybar_base=../../style/style-mauve
waybar_shape=noop
waybar_accent=noop
gtk_theme=adw-gtk3-dark
bg=#1e1e2e
fg=#cba7f7
muted=#8981c1
accent=#cba6f7
accent_alt=#9ccfd8
warm=#f9e2af
ok=#a6e3a1
critical=#e46876
