waybar_palette=cyber-mint
waybar_base=../../style/style-rgb
waybar_shape=noop
waybar_accent=noop
gtk_theme=adw-gtk3-dark
bg=#1e1e2e
fg=#cdd6f4
muted=#6e6a86
accent=#b4befe
accent_alt=#94e2d5
warm=#fab387
ok=#a6e3a1
critical=#f38ba8
