waybar_palette=omarchy-tokyo-night
waybar_base=../../style/style-default1
waybar_shape=noop
waybar_accent=noop
gtk_theme=adw-gtk3-dark
bg=#1a1b26
fg=#ffffff
muted=#7984a4
accent=#b4befe
accent_alt=#cba7f7
warm=#ebcb8b
ok=#90ee90
critical=#f53c3c
