waybar_palette=omarchy-matte-black
waybar_base=omarchy-strip
waybar_shape=zero-bar
waybar_accent=minimal-icons
gtk_theme=adw-gtk3-dark
theme_mode=dark
bg=#121212
fg=#eaeaea
muted=#5a5a5a
accent=#e68e0d
accent_alt=#f59e0b
warm=#ffc107
ok=#879a39
critical=#d14d41
