waybar_palette=omarchy-vantablack
waybar_base=omarchy-strip
waybar_shape=zero-bar
waybar_accent=minimal-icons
gtk_theme=adw-gtk3-dark
bg=#000000
fg=#ffffff
muted=#404040
accent=#8d8d8d
accent_alt=#b0b0b0
warm=#cecece
ok=#b6b6b6
critical=#a4a4a4
