#!/bin/bash

watch_layout() {
  socat -U - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" |
  while read -r line; do
    case "$line" in
      activelayout*)
        LAYOUT=${line#*,}
        SHORT=$(echo "$LAYOUT" | cut -c1-2 | tr '[:lower:]' '[:upper:]')

        swayosd-client \
          --custom-message "$SHORT" \
          # --custom-icon input-keyboard
        ;;
    esac
  done
}

watch_layout &
wait
