#!/bin/bash

DIR="$HOME/Pictures/Wallpapers"
WOFI_CONFIG="$HOME/.config/wofi/config-clipboard"
WOFI_STYLE="$HOME/.config/wofi/style-compact.css"
WOFI_COLORS="$HOME/.config/wofi/colors"

# 1. Собираем файлы
mapfile -t PICS < <(find "$DIR" -maxdepth 1 -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.webp" \))

# 2. Функция генерации меню с фиксом амперсанда
menu(){
    for i in "${!PICS[@]}"; do
        # Заменяем & на &amp; чтобы wofi не давился
        filename=$(basename "${PICS[$i]}" | sed 's/&/\&amp;/g')
        echo "$i. $filename"
    done
    echo "RANDOM"
}

# 3. Команда wofi
wofi_command=(
    wofi --dmenu
    --conf "$WOFI_CONFIG"
    --style "$WOFI_STYLE"
    --color "$WOFI_COLORS"
    --prompt 'Wallpaper'
    --cache-file=/dev/null
)

is_hyprland() {
    [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ] && hyprctl monitors >/dev/null 2>&1
}

apply_hyprpaper() {
    local file="$1"
    local CONF="$HOME/.config/hypr/hyprpaper.conf"

    if [ -f "$CONF" ]; then
        sed -i 's/ipc = off/ipc = on/g' "$CONF"
    fi

    if ! pgrep -x "hyprpaper" > /dev/null; then
        hyprpaper &
        sleep 0.5
    fi

    hyprctl hyprpaper preload "$file"

    MONITORS=$(hyprctl monitors | grep "Monitor" | awk '{print $2}')
    for mon in $MONITORS; do
        hyprctl hyprpaper wallpaper "$mon,$file"
    done

    hyprctl hyprpaper unload unused
}

apply_awww() {
    local file="$1"

    pkill swaybg
    pkill hyprpaper
    awww query || { awww-daemon & sleep 0.5; }
    awww img "$file" --transition-fps 30 --transition-type any --transition-duration 3
}

apply() {
    local file
    file=$(realpath "$1")

    if is_hyprland; then
        apply_hyprpaper "$file"
    else
        apply_awww "$file"
    fi
}

# 4. Запуск
choice=$(menu | "${wofi_command[@]}")

if [[ -z $choice ]]; then exit 0; fi

if [[ "$choice" == "RANDOM" ]]; then
    target="${PICS[$RANDOM % ${#PICS[@]}]}"
    apply "$target"
else
    # Извлекаем индекс (цифры в начале)
    idx=$(echo "$choice" | grep -o '^[0-9]\+')
    target="${PICS[$idx]}"
    apply "$target"
fi
