model:
  provider: custom:wb-corellm-coder
  base_url: ''
  default: wb-coder
  context_length: 202752
agent:
  max_turns: 150
display:
  tool_progress: all
  timestamps: true
  skin: default
_config_version: 33
session_reset:
  mode: none
onboarding:
  seen:
    tool_progress_prompt: true
    busy_input_prompt: true
custom_providers:
  - name: wb-corellm-coder
    base_url: https://corellm.wb.ru/coder/v1
    key_env: CORELLM_API_KEY
    api_mode: chat_completions
    models:
      wb-coder:
        context_length: 202752
      glm-51:
        context_length: 202752
  - name: wb-corellm-reviewer-a
    base_url: https://aimodels.wb.ru/reviewer-a/v1
    key_env: CORELLM_API_KEY
    api_mode: chat_completions
    models:
      berrylm-l:
        context_length: 262144
  - name: wb-corellm-reviewer-b
    base_url: https://aimodels.wb.ru/reviewer-b/v1
    key_env: CORELLM_API_KEY
    api_mode: chat_completions
    models:
      berrylm-l-v2:
        context_length: 262144
  - name: llama-cpp
    base_url: http://compik.home:7070/v1
    api_mode: chat_completions
    models:
      qwen3.6-35b-a3b:
        context_length: 80072
      Qwen3-Coder-Next-UD-Q4_K_M-80072:
        context_length: 80072
      Qwen3-Coder-Next-UD-Q4_K_M-262144:
        context_length: 162144
      Qwen3-Coder-Next-UD-Q4_K_M-162144:
        context_length: 162144
