
splash = true # enable rendering of the hyprland splash over the wallpaper
splash_offset = 20 # how far up should the splash be displayed
splash_opacity = 0.8 # how opaque the splash is
ipc = true # enable ipc for hyprpaperctl and other tools

# wallpaper {
#     monitor = DP-3
#     path = ~/myFile.jxl
#     fit_mode = cover # contain|cover|tile|fill
#     timeout = 300 # in seconds
# }

# wallpaper {
#     monitor = DP-2
#     path = ~/myFile2.jxl
#     fit_mode = cover
# }

# wallpaper {
#     monitor = 
#     path = ~/fallback.jxl
#     fit_mode = cover
# }
