# Стиль Kanagawa Dragon
timeout = 1000
width = 600
height = 40
border_offset = 2
border_size = 2
bar_padding = 2
anchor = top center
margin = 55

# Цвета (HEX без #, формат RRGGBBAA)
background_color = 181820ee ; #181820ee
bar_color = 859aca ; #859aca
border_color = 859aca ; #859aca