#!/bin/bash

CACHED_CONFIG="${XDG_CACHE_HOME:-$HOME/.cache}/waybar/config"
CONFIG="$HOME/.config/waybar/config"
STYLE="$HOME/.config/waybar/style.css"

if [[ -s "$CACHED_CONFIG" ]]; then
	CONFIG="$CACHED_CONFIG"
fi

if [[ ! $(pidof waybar) ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
