# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Autostart Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

source = ~/.config/hypr/config/defaults.conf

exec-once = waybar &
exec-once = hyprpaper &
# exec-once = $scriptsDir/startup

exec-once = fcitx5 -d &
# exec-once = mako &
exec-once = swaync & # notification center
exec-once = nm-applet --indicator & blueman-applet & # network manager and bluetooth
exec-once = bash -c "rm -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob -c ~/.config/wob/wob.ini" # volume and brightness OSD
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &

## Slow app launch fix
exec-once = systemctl --user import-environment &
exec-once = hash dbus-update-activation-environment 2>/dev/null &
exec-once = dbus-update-activation-environment --systemd &

## Idle configuration
exec-once = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'

## clipboard manager 
exec-once = wl-clip-persist --clipboard regular
# cliphist
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-paste --watch cliphist store
# # exec-once = cliphist wipe; wl-paste --watch cliphist store
## exec-once = wl-paste --watch clipvault store
## exec-once = wl-paste --type text --watch clipvault store
## exec-once = wl-paste --type image --watch clipvault store
## exec-once = wl-paste --watch clipvault store --min-entry-length 2 --max-entries 200 --max-entry-age 2d


# autostart applications
exec-once = [workspace 2 silent] $browser
exec-once = [workspace 3 silent] $IDE
# exec-once = [workspace 4 silent] $workMessenger
exec-once = [workspace 6 silent] $telegram
exec-once = $scriptsDir/launch-band
