# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# See https://wiki.hypr.land/Configuring/Keywords/

$scriptsDir = $HOME/.config/hypr/scripts

# Set programs that you use
# $terminal = kitty
$fileManager = nautilus
$menu = hyprlauncher
# $menu = bemenu
$browser = zen-browser
# $browser = chromium
$IDE = code
$telegram = forkgram
$workMessenger = ~/Applications/band-desktop*.AppImage
# $workMessenger = Band


# $filemanager = 
$applauncher = rofi -show combi -modi window,run,combi -combi-modi window,run
$terminal = alacritty
$idlehandler = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'
$capturing = grim -g "$(slurp)" - | swappy -f -
$fullCapturing = @scriptsDir/screenshot_full

$waybar-style = @scriptsDir/waybar-style-change
