# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# See https://wiki.hypr.land/Configuring/Keywords/

$scriptsDir = $HOME/.config/hypr/scripts
$desktopScriptsDir = $HOME/.config/desktop/scripts
$waybarScriptsDir = $HOME/.config/waybar/scripts

# Set programs that you use
$terminal = alacritty
$fileManager = nautilus
# $menu = hyprlauncher
# $menu = wofi -I -G
$menu = $desktopScriptsDir/menu
$browser = zen-browser
# $browser = chromium
$IDE = code
$telegram = forkgram
$workMessenger = ~/Applications/band-desktop*.AppImage

$screenshotDir = ~/Pictures/Screenshots

